Add a command-line flag to specify enrollment term
k-walter/canvas-downloader pull request #22
Opened 2023-01-13 07:20 UTC by parth-io

2023-01-13 19:05 UTC, k-walter requested changes

2023-01-13 19:05 UTC, k-walter commented on README.md
> +- By default, the downloader will download all active courses, even from previous terms. Use the `-i` flag with a specific term_id to choose a specific enrollment month (`120` for Jan 2023, for examp
Go all the way down for some ideas on how we can display and choose term ID.

2023-01-13 19:05 UTC, k-walter commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
I'm thinking we can allow for `-i` to list the terms+ID from that API, and `-i 119 120 121` to opt in to multiple terms.

We can do this by using this, then checking for `enrollment_term_id.is_empty()` to query that API.
```rust
enrollment_term_id: Vec<u32>,
```

What do you think? @JingYenLoh @bnjmnt4n

2023-01-13 19:39 UTC, k-walter commented on src/main.rs
> +            !args.enrollment_term_id.is_some() || (args.enrollment_term_id.unwrap_or_else(|| {
Also, allow me introduce you to clippy
```sh
$ cargo clippy
warning: this boolean expression can be simplified
  --> src/main.rs:55:13
   |
55 |             !args.enrollment_term_id.is_some() || (args.enrollment_term_id.unwrap_or_else(|| {
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `args.enrollment_term_id.is_none()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#nonminimal_bool
   = note: `#[warn(clippy::nonminimal_bool)]` on by default

warning: deref which would be done by auto-deref
  --> src/main.rs:57:19
   |
57 |             }) == (*course_json).enrollment_term_id)
   |                   ^^^^^^^^^^^^^^ help: try this: `course_json`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
   = note: `#[warn(clippy::explicit_auto_deref)]` on by default
```
and `rustfmt`
```sh
$ cargo fmt --check
Diff in /home/walt/dev/canvas-downloader/src/main.rs at line 52:
             })
         })
         .filter(|course_json: &canvas::Course| {
-            !args.enrollment_term_id.is_some() || (args.enrollment_term_id.unwrap_or_else(|| {
-                panic!("Invalid enrollment term id provided")
-            }) == (*course_json).enrollment_term_id)
+            !args.enrollment_term_id.is_some()
+                || (args
+                    .enrollment_term_id
+                    .unwrap_or_else(|| panic!("Invalid enrollment term id provided"))
+                    == (*course_json).enrollment_term_id)
         })
         .collect();
```

2023-01-16 15:30 UTC, parth-io commented on README.md
> +- By default, the downloader will download all active courses, even from previous terms. Use the `-i` flag with a specific term_id to choose a specific enrollment month (`120` for Jan 2023, for examp
Ah, my bad

2023-01-16 15:36 UTC, parth-io commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
Hmm interesting, I can implement this.

An alternative is to enter the start and end dates, and then to check for `enrollment_term_id`s from `https://canvas.nus.edu.sg/api/v1/accounts/1/terms?include[]=overrides` that match the start and end dates. This can also solve the problem of specifying multiple terms ids that can change. There's the cost of an additional API call, unless we store the  `enrollment_term_id`s locally and add another flag to force-refresh this local storage manually whenever desired

2023-01-17 03:45 UTC, k-walter commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
@parth-io
> additional API call

The request for courses actually returns `enrollment_term_id` as you mentioned. Perhaps we could use the set of terms given?

However, since the term's name is not included, we could help users decide by listing the courses belonging to that term? Eg with `println!("{: <10}|{}")`
```
Term      | Courses
120       | CS2040S, CS2106
115       | CS1101S, CS1231
```

2023-01-17 11:44 UTC, parth-io commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
That's a lot better actually

2023-01-17 11:58 UTC, k-walter commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
On second thoughts, let's exit after showing the table, so that users will run again with the proper terms and it's stored in their history. I'd prefer to keep input parsing to clap too.

2023-01-28 08:58 UTC, k-walter commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
@parth-io Hey I'd like to merge this PR soon. I can help you with this implementation if you'd like.

2023-01-28 15:22 UTC, parth-io commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
Hey I'm sorry, I haven't had a chance to work on this yet. I'll submit a commit later tomorrow

2023-01-30 18:52 UTC, parth-io commented on README.md
> +- `./canvas-downloader -i <TERM ID> -u <CANVAS URL> -t <CANVAS API TOKEN> -d <DESTINATION FOLDER>`
The documentation seems a bit messy, I can re-word it in a separate PR

2023-01-30 18:52 UTC, parth-io commented on src/main.rs
> +    #[clap(short = 'i', long, multiple_values = true)]
Note that this is for `clap` v3.0. For `clap` v4.0, we should use `num_args(1..)`. I can upgrade clap in a separate PR as well

2023-01-30 18:52 UTC, parth-io commented on src/main.rs
> +        if let Some(arg) = temp.next() {
Is there a more idiomatic way to do this in Rust?

2023-01-30 18:52 UTC, parth-io commented on src/main.rs
> +    if courses_matching_term_ids.is_empty() {
An additional behaviour here that also prints the term ids with the courses, if the user has provided some term ids but they cannot be found in the downloaded courses. This may have happened if for example the user made a typo at the command-line when writing the flag

2023-01-30 18:54 UTC, parth-io commented on src/main.rs
> +    enrollment_term_id: Option<u32>,
Submitted!

2023-01-30 19:11 UTC, k-walter commented on src/main.rs
> +    #[clap(short = 'i', long, multiple_values = true)]
Well actually if there are no breaking changes in clap, feel free to upgrade the version in this PR. I'm planning on removing some arguments in a major release.

2023-01-30 19:17 UTC, k-walter commented on src/main.rs
> +    let mut grouped_courses: Vec<canvas::CoursesWithId> = Vec::new();
Consider using `std::collections::HashMap`

2023-01-30 19:20 UTC, k-walter commented on src/main.rs
> +    pub struct CoursesWithId<'a> {
Use a HashMap. Let's keep struct to represent external API or important data structures.

2023-01-30 19:23 UTC, k-walter commented on src/main.rs
> +        if let Some(arg) = temp.next() {
Yep, `Vec` implements `Debug`, so you can `println!("{courses_with_id:?}");`

2023-01-31 15:52 UTC, parth-io commented on src/main.rs
> +    #[clap(short = 'i', long, multiple_values = true)]
Oh there are quite a few breaking changes for the other arguments as well

I'll take a look at it later

2023-01-31 16:00 UTC, parth-io commented on src/main.rs
> +    let mut grouped_courses: Vec<canvas::CoursesWithId> = Vec::new();
Yep, that's certainly better than a double for loop

2023-02-01 13:33 UTC, k-walter commented on src/main.rs
> +        .collect::<Vec<&canvas::Course>>();
Nitpick: It's sufficient to specify type on line 67.

No fix needed.

2023-02-01 13:35 UTC, k-walter commented on src/main.rs
> +    let mut grouped_courses: HashMap<u32, Vec<&String>> = HashMap::new();
FYI
1. it's idiomatic to use `&str` for non-owning reference to strings.
2. You can actually choose not to specify the type, because the compiler can guess it :)

2023-02-01 13:35 UTC, k-walter commented on src/main.rs
> +            .push(&course.course_code);
Nice!

2023-02-01 13:41 UTC, k-walter commented on src/main.rs
> +        "Please specify the correct term ids as per the list below\nTerm IDs  | \
Not sure if "correct" is the word to use here. Maybe

> Please provide the Term ID(s) to download via -i\n...

2023-02-01 13:52 UTC, merged

2023-02-01 13:53 UTC, k-walter commented
Thanks for the help! @parth-io

2023-02-01 14:07 UTC, parth-io commented
Sure, thanks for taking the time to review the code and providing useful tips along the way!